USE [master]
GO

/****** Object:  Database [ecommerce]    Script Date: 08/03/2022 18:16:05 ******/
CREATE DATABASE [ecommerce]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ecommerce', FILENAME = N'/var/opt/mssql/data/ecommerce.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ecommerce_log', FILENAME = N'/var/opt/mssql/data/ecommerce_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ecommerce].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ecommerce] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ecommerce] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ecommerce] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ecommerce] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ecommerce] SET ARITHABORT OFF 
GO

ALTER DATABASE [ecommerce] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ecommerce] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ecommerce] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ecommerce] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ecommerce] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ecommerce] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ecommerce] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ecommerce] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ecommerce] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ecommerce] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ecommerce] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ecommerce] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ecommerce] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ecommerce] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ecommerce] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ecommerce] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ecommerce] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ecommerce] SET RECOVERY FULL 
GO

ALTER DATABASE [ecommerce] SET  MULTI_USER 
GO

ALTER DATABASE [ecommerce] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ecommerce] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ecommerce] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ecommerce] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ecommerce] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ecommerce] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ecommerce] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ecommerce] SET  READ_WRITE 
GO